name: Get Joke

on:
  workflow_dispatch:
  push:
    

jobs:
  get-joke:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Joke
      run: |
        JSON_PAYLOAD=$(jq -n \
          --arg system_content "Tell me a really funny and unique joke for software developers and DevOps engineers. Make sure it's clever, uses relevant programming or DevOps terminology, and is fresh and original." \
          --arg user_content "" \
          '{
            "model": "gpt-4",
            "messages": [
              {
                "role": "system",
                "content": $system_content
              },
              {
                "role": "user",
                "content": $user_content
              }
            ],
            "temperature": 0.7,
            "max_tokens": 60,
            "top_p": 1,
            "frequency_penalty": 0.5,
            "presence_penalty": 0.3
          }')

        RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{secrets.OPENAI_API_KEY}}" \
          -d "$JSON_PAYLOAD")
          
        echo "OpenAI Response: $RESPONSE"
          
        
