name: Get Joke

on:
  workflow_dispatch:
  push:
    

jobs:
  get-joke:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Joke
      run: |
        # Array of random topics to add variety
        topics=("debugging" "cloud infrastructure" "automation" "version control" "containers")
        
        # Randomly select a topic
        RANDOM_TOPIC=${topics[$RANDOM % ${#topics[@]}]}
        
        # Create the prompt
        PROMPT="Tell me a really funny and unique joke for software developers and DevOps engineers about ${RANDOM_TOPIC}. Make it clever, relevant to programming or DevOps, and fresh every time."
        
        JSON_PAYLOAD=$(jq -n \
          --arg system_content "$PROMPT" \
          --arg user_content "" \
          '{
            "model": "gpt-4",
            "messages": [
              {
                "role": "system",
                "content": $system_content
              },
              {
                "role": "user",
                "content": $user_content
              }
            ],
            "temperature": 0.9,
            "max_tokens": 60,
            "top_p": 1,
            "frequency_penalty": 0.8,
            "presence_penalty": 0.5
          }')

        RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{secrets.OPENAI_API_KEY}}" \
          -d "$JSON_PAYLOAD")
          
        echo "OpenAI Response: $RESPONSE"
        
        # Extract the joke from the response
        JOKE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content' | sed '/^\s*$/d')
        
        # Print the joke
        echo "Here's your joke:"
        echo "$JOKE"
        
        # Define your image prompt
        PROMPT="You are a instagram influencer and content creator for developers and engineers. Create a background image for the following joke: $JOKE"
        
        # Call the DALL·E API
        RESPONSE=$(curl -s https://api.openai.com/v1/images/generations \
          -H "Authorization: Bearer ${{secrets.OPENAI_API_KEY}}" \
          -H "Content-Type: application/json" \
          -d '{
            "prompt": "'"$PROMPT"'",
            "n": 1,
            "size": "1080x1920"
          }')

        echo "OpenAI Response: $RESPONSE"
        
        # Extract the URL of the generated image
        IMAGE_URL=$(echo "$RESPONSE" | jq -r '.data[0].url')
        
        # Output the image URL
        echo "Generated Image URL: $IMAGE_URL"
          
        
