name: Get Joke

on:
  workflow_dispatch:
  push:
    

jobs:
  get-joke:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Joke
      run: |
        JSON_PAYLOAD=$(jq -n \
          --arg system_content "I am a developer. Tell me a joke that I find really funny. Tell me a new joke every time I ask." \
          --arg user_content "" \
          '{
            "model": "gpt-4o",
            "messages": [
              {
                "role": "system",
                "content": $system_content
              },
              {
                "role": "user",
                "content": $user_content
              }
            ],
            "temperature": 1,
            "max_tokens": 256,
            "top_p": 1,
            "frequency_penalty": 0,
            "presence_penalty": 0
          }')

        RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{secrets.OPENAI_API_KEY}}" \
          -d "$JSON_PAYLOAD")
          
        echo "OpenAI Response: $RESPONSE"
          
        
